# Generated by Django 6.1 on 2026-08-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
        ('stocks', '0003_companyrevenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrevenue',
            name='account_number',
            field=models.CharField(default='', help_text="The user's shares wallet number that was charged.", max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companyrevenue',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_charges', to='transactions.transaction'),
        ),
    ]
