# Generated by Django 6.1 on 2026-08-14 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_add_charge_trace'),
        ('transactions', '0008_backfill_transaction_references'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyrevenue',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='The trade transaction this charge belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_charges', to='transactions.transaction'),
        ),
    ]
