# Generated by Django 6.1 on 2026-08-14 11:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_companyrevenue_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrevenue',
            name='investor_balances_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot of the total balances across all investor share wallets at the time of the charge.', max_digits=15),
        ),
        migrations.AddField(
            model_name='companyrevenue',
            name='outflow',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Any cash paid out by the company on this entry (e.g. dividends/payouts). 0 for a charge.', max_digits=15),
        ),
        migrations.AddField(
            model_name='companyrevenue',
            name='total_collected',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross amount collected from the investor in this trade (buy: total cost incl. charges; sell: gross proceeds).', max_digits=15),
        ),
        migrations.AddField(
            model_name='companyrevenue',
            name='user_deposit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Snapshot of the trading user's main account balance at the time of the charge.", max_digits=15),
        ),
    ]
