# Generated by Django 6.1 on 2026-08-14 11:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_companyrevenue_investor_balances_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrevenue',
            name='app_total_charges',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running total of all transaction charges collected by the company across every user so far (including this charge).', max_digits=15),
        ),
        migrations.AddField(
            model_name='companyrevenue',
            name='total_invested_chamas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total money all members have contributed to chamas.', max_digits=15),
        ),
        migrations.AddField(
            model_name='companyrevenue',
            name='total_invested_goals',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total money all users have saved toward goals.', max_digits=15),
        ),
        migrations.AddField(
            model_name='companyrevenue',
            name='total_invested_stocks',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total cost-basis of all shares held across every investor.', max_digits=15),
        ),
    ]
