# Generated by Django 6.1 on 2026-08-14 12:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_companyrevenue_app_total_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrevenue',
            name='charge_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Percentage rate that produced this charge (e.g. 2.000).', max_digits=6),
        ),
        migrations.AddField(
            model_name='companyrevenue',
            name='charge_type',
            field=models.CharField(default='stocks', help_text="What kind of transaction produced this charge (e.g. 'transfer', 'withdrawal', 'goal_funding', 'chama_contribution', 'chama_join', 'stocks').", max_length=40),
        ),
    ]
