# Generated by Django 4.2.30 on 2026-08-08 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contribution_frequency', models.CharField(default='weekly', max_length=20)),
                ('total_pool_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('member_count', models.IntegerField(default=1)),
                ('invite_code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChamaMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('chama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='chamas.chama')),
            ],
        ),
    ]
