# Generated by Django 6.1 on 2026-08-13 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamamembership',
            name='contributed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount this member has contributed to the chama pool', max_digits=15),
        ),
    ]
