# Generated by Django 6.1 on 2026-08-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biller',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='biller',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='Subtitle/secondary text for the biller', max_length=200),
        ),
        migrations.AddField(
            model_name='biller',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Display title for the biller', max_length=100),
        ),
        migrations.AlterField(
            model_name='biller',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='biller',
            name='category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
