# Generated by Django 6.1 on 2026-08-13 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_account_type_alter_account_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(help_text='Recipient phone number', max_length=20)),
                ('account_number', models.CharField(blank=True, default='', max_length=50)),
                ('bank_name', models.CharField(blank=True, default='', help_text='Bank name for bank beneficiaries', max_length=100)),
                ('is_bank', models.BooleanField(default=False, help_text='True for bank transfers, False for mobile money')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'phone_number')},
            },
        ),
    ]
