# Generated by Django 6.1 on 2026-08-20 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_biller_balance_account_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, help_text="User's bank account number this card is linked to", max_length=50)),
                ('card_number', models.CharField(blank=True, help_text='Full card number (auto-generated, masked on display)', max_length=16, unique=True)),
                ('card_type', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'American Express')], default='visa', max_length=20)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('expiry_date', models.CharField(help_text='Format: MM/YY', max_length=5)),
                ('cvv', models.CharField(help_text='Stored encrypted (last 3 digits)', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('frozen', 'Frozen'), ('expired', 'Expired'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('spend_limit', models.DecimalField(decimal_places=2, default=100000.0, help_text='Daily spend limit in KSh', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Card',
                'verbose_name_plural': 'Credit Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, help_text="User's bank account number this card is linked to", max_length=50)),
                ('card_number', models.CharField(blank=True, help_text='Full card number (auto-generated, masked on display)', max_length=16, unique=True)),
                ('card_type', models.CharField(choices=[('visa_debit', 'Visa Debit'), ('mastercard_debit', 'MasterCard Debit'), ('virtual', 'Virtual Debit')], default='virtual', max_length=20)),
                ('cardholder_name', models.CharField(max_length=100)),
                ('expiry_date', models.CharField(help_text='Format: MM/YY', max_length=5)),
                ('cvv', models.CharField(help_text='Stored encrypted (last 3 digits)', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('frozen', 'Frozen'), ('expired', 'Expired'), ('blocked', 'Blocked')], default='pending', max_length=20)),
                ('spend_limit', models.DecimalField(decimal_places=2, default=50000.0, help_text='Daily spend limit in KSh', max_digits=12)),
                ('is_contactless', models.BooleanField(default=True, help_text='Enable/contactless payments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debit Card',
                'verbose_name_plural': 'Debit Cards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_payments_enabled', models.BooleanField(default=True, help_text='Enable online card payments')),
                ('contactless_enabled', models.BooleanField(default=True, help_text='Enable contactless payments')),
                ('sms_notifications', models.BooleanField(default=True, help_text='SMS transaction notifications')),
                ('email_notifications', models.BooleanField(default=True, help_text='Email transaction notifications')),
                ('total_daily_spend_limit', models.DecimalField(decimal_places=2, default=150000.0, help_text='Total daily spend limit across all cards in KSh', max_digits=12)),
                ('low_spend_alert', models.DecimalField(decimal_places=2, default=10000.0, help_text='Spend alert threshold in KSh', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_credit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_user', to='accounts.creditcard')),
                ('default_debit_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_user', to='accounts.debitcard')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Card Settings',
                'verbose_name_plural': 'User Card Settings',
            },
        ),
    ]
