# Generated by Django 6.1 on 2026-08-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_creditcard_debitcard_usercardsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'American Express'), ('virtual', 'Virtual')], default='visa', max_length=20),
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='card_type',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'American Express'), ('virtual', 'Virtual')], default='virtual', max_length=20),
        ),
    ]
