# Generated by Django 6.1 on 2026-08-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_creditcard_card_type_alter_debitcard_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='reason_for_applying',
            field=models.CharField(blank=True, help_text='Reason why the card is being applied for', max_length=200),
        ),
        migrations.AddField(
            model_name='debitcard',
            name='reason_for_applying',
            field=models.CharField(blank=True, help_text='Reason why the card is being applied for', max_length=200),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='cvv',
            field=models.CharField(help_text='System-generated CVV', max_length=3),
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='cvv',
            field=models.CharField(help_text='System-generated CVV', max_length=3),
        ),
    ]
