import re

from django.contrib.auth import get_user_model
from django.test import TestCase
from django.utils import timezone
from rest_framework.test import APIClient

from .models import Transaction

User = get_user_model()

REFERENCE_PATTERN = re.compile(r'^[A-Z0-9]{10,12}$')


class TransactionReferenceTests(TestCase):
    def setUp(self):
        self.client = APIClient()
        self.user = User.objects.create_user(
            username='refuser',
            email='ref@example.com',
            password='testpass123',
            balance='10000.00',
        )
        self.client.force_authenticate(user=self.user)

    def _create_transaction(self):
        return Transaction.objects.create(
            user=self.user,
            amount='500.00',
            category='deposit',
            type='deposit',
            description='Test transaction',
            date=timezone.now(),
        )

    def test_reference_is_autogenerated(self):
        txn = self._create_transaction()
        self.assertTrue(REFERENCE_PATTERN.match(txn.reference))

    def test_reference_is_uppercase_alphanumeric_length_10_to_12(self):
        for _ in range(20):
            txn = self._create_transaction()
            self.assertRegex(txn.reference, REFERENCE_PATTERN)
            self.assertTrue(10 <= len(txn.reference) <= 12)

    def test_references_are_unique(self):
        refs = {self._create_transaction().reference for _ in range(10)}
        self.assertEqual(len(refs), 10)

    def test_deposit_endpoint_returns_reference(self):
        response = self.client.post('/api/transactions/deposit/', {
            'user': self.user.id,
            'amount': '1000.00',
        })
        self.assertEqual(response.status_code, 201)
        reference = response.json()['reference']
        self.assertRegex(reference, REFERENCE_PATTERN)
        self.assertEqual(Transaction.objects.get(reference=reference).amount, 1000.00)

    def test_withdraw_endpoint_returns_reference(self):
        response = self.client.post('/api/transactions/withdraw/', {
            'user': self.user.id,
            'amount': '1000.00',
        })
        self.assertEqual(response.status_code, 201)
        reference = response.json()['reference']
        self.assertRegex(reference, REFERENCE_PATTERN)

    def test_transfer_endpoint_returns_reference(self):
        recipient = User.objects.create_user(
            username='refrecipient',
            email='refrecipient@example.com',
            password='testpass123',
            phone_number='+254700000001',
            balance='0.00',
        )
        response = self.client.post('/api/transactions/transfer/', {
            'sender': self.user.id,
            'recipient_phone': recipient.phone_number,
            'amount': '500.00',
        })
        self.assertEqual(response.status_code, 201)
        reference = response.json()['reference']
        self.assertRegex(reference, REFERENCE_PATTERN)

    def test_serializer_exposes_reference(self):
        txn = self._create_transaction()
        response = self.client.get(f'/api/transactions/?user={self.user.id}')
        self.assertEqual(response.status_code, 200)
        data = response.json()
        self.assertTrue(any(t['id'] == txn.id and t['reference'] == txn.reference for t in data))
