from django.db import models
from django.conf import settings
from django.utils import timezone
import uuid


class MpesaPayment(models.Model):
    """Tracks M-Pesa STK Push transactions.

    A row is created when an STK Push is initiated.  It is updated when
    Safaricom sends the callback (or when the status is polled).
    """

    class Status(models.TextChoices):
        PENDING = 'pending', 'Pending'
        SUCCESS = 'success', 'Success'
        FAILED = 'failed', 'Failed'
        CANCELLED = 'cancelled', 'Cancelled'

    class ItemType(models.TextChoices):
        BUY_GOODS = 'buy_goods', 'Buy Goods / Till'
        BUY_GOODS_SERVICES = 'buy_goods_services', 'Buy Goods and Services'
        PAYBILL = 'paybill', 'Paybill'

    # --- Core tracking fields ---
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='mpesa_payments',
    )
    reference = models.CharField(
        max_length=64,
        unique=True,
        help_text='Unique reference generated by Alexia for this STK request.',
    )

    # Daraja response identifiers
    merchant_request_id = models.CharField(max_length=255, blank=True)
    checkout_request_id = models.CharField(max_length=255, blank=True)

    # --- What the user is paying for ---
    item_type = models.CharField(
        max_length=20, choices=ItemType.choices
    )
    item_id = models.CharField(
        max_length=20,
        help_text='Till number (Buy Goods) or Paybill number.',
    )
    account_reference = models.CharField(
        max_length=100, blank=True,
        help_text='Account reference / number for Paybill.',
    )

    # --- Payment details ---
    phone_number = models.CharField(max_length=20)
    amount = models.DecimalField(max_digits=15, decimal_places=2)
    transaction_desc = models.TextField(blank=True)

    # --- Status / result ---
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.PENDING,
    )
    result_code = models.CharField(max_length=10, blank=True)
    result_desc = models.TextField(blank=True)
    mpesa_receipt_number = models.CharField(max_length=50, blank=True)

    # --- Links to the ledger Transaction ---
    ledger_transaction = models.ForeignKey(
        'transactions.Transaction',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='mpesa_payment',
    )

    # --- Timestamps ---
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    completed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['-created_at']),
            models.Index(fields=['checkout_request_id']),
            models.Index(fields=['status']),
        ]

    def __str__(self):
        return f'{self.get_item_type_display()} {self.amount} – {self.status}'

    def mark_completed(self, mpesa_receipt_number=None):
        self.status = self.Status.SUCCESS
        self.mpesa_receipt_number = mpesa_receipt_number or self.mpesa_receipt_number
        self.result_code = '0'
        self.result_desc = 'The service request was accepted successfully.'
        self.completed_at = timezone.now()
        self.save(update_fields=[
            'status', 'mpesa_receipt_number', 'result_code',
            'result_desc', 'completed_at', 'updated_at',
        ])

    def mark_failed(self, code, desc):
        if self.status != self.Status.SUCCESS:
            self.status = self.Status.FAILED
            self.result_code = str(code)
            self.result_desc = desc
            self.completed_at = timezone.now()
            self.save(update_fields=[
                'status', 'result_code', 'result_desc',
                'completed_at', 'updated_at',
            ])

    def mark_cancelled(self):
        if self.status == self.Status.PENDING:
            self.status = self.Status.CANCELLED
            self.result_desc = 'Customer cancelled the STK request.'
            self.completed_at = timezone.now()
            self.save(update_fields=[
                'status', 'result_desc', 'completed_at', 'updated_at',
            ])
