# Generated by Django 6.1 on 2026-08-14 06:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('product_type', models.CharField(choices=[('treasury_bill', 'Treasury Bill'), ('money_market_fund', 'Money Market Fund'), ('balanced_unit_trust', 'Balanced Unit Trust')], max_length=30)),
                ('tagline', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('annual_rate', models.DecimalField(decimal_places=3, help_text='Gross annualized rate in % (e.g. latest T-bill auction rate).', max_digits=6)),
                ('fee_percent', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Deduction % taken before the investor is paid (service/management fee).', max_digits=6)),
                ('tenure_days', models.PositiveIntegerField(default=91, help_text='Maturity / projection period in days.')),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_best_match', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_best_match', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('maturity_value', models.DecimalField(decimal_places=2, help_text='Gross payout before deduction.', max_digits=15)),
                ('fee_deducted', models.DecimalField(decimal_places=2, help_text='Amount deducted from the investor before payout.', max_digits=15)),
                ('net_payout', models.DecimalField(decimal_places=2, help_text='What the investor actually receives at maturity.', max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('invested_at', models.DateTimeField(auto_now_add=True)),
                ('maturity_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='investments.investmentproduct')),
            ],
            options={
                'ordering': ['-invested_at'],
            },
        ),
    ]
