# Generated by Django 6.1 on 2026-08-14 08:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investmentwallet_investment_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='interest_accrued',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Interest earned so far (money market funds accrue daily).', max_digits=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='last_accrual_date',
            field=models.DateTimeField(blank=True, help_text='Last time daily interest was deposited for this investment.', null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='maturity_date',
            field=models.DateTimeField(blank=True, help_text='Maturity for fixed-term products; money market funds are open-ended.', null=True),
        ),
    ]
