# Generated by Django 4.2.30 on 2026-08-15 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0002_seed_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('signup', 'Welcome Bonus'), ('referral', 'Referral Reward'), ('deposit', 'Money Deposit'), ('investment', 'Investment'), ('goal_saving', 'Savings Goal Deposit')], max_length=20)),
                ('points', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('key', models.CharField(help_text='Unique event key so each award is granted only once.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
