# Generated by Django 6.1 on 2026-08-16 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0009_transaction_broker_fee_transaction_government_tax'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Unique reference generated by Alexia for this STK request.', max_length=64, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=255)),
                ('checkout_request_id', models.CharField(blank=True, max_length=255)),
                ('item_type', models.CharField(choices=[('buy_goods', 'Buy Goods (Till)'), ('paybill', 'Paybill')], max_length=20)),
                ('item_id', models.CharField(help_text='Till number (Buy Goods) or Paybill number.', max_length=20)),
                ('account_reference', models.CharField(blank=True, help_text='Account reference / number for Paybill.', max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_desc', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('result_code', models.CharField(blank=True, max_length=10)),
                ('result_desc', models.TextField(blank=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ledger_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payment', to='transactions.transaction')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='mpesa_mpesa_created_75ddec_idx'), models.Index(fields=['checkout_request_id'], name='mpesa_mpesa_checkou_38cbc1_idx'), models.Index(fields=['status'], name='mpesa_mpesa_status_dafcb6_idx')],
            },
        ),
    ]
