# Generated by Django 6.1 on 2026-08-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='item_type',
            field=models.CharField(choices=[('buy_goods', 'Buy Goods / Till'), ('buy_goods_services', 'Buy Goods and Services'), ('paybill', 'Paybill')], max_length=20),
        ),
    ]
