# Generated by Django 6.1 on 2026-08-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_billercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='account_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
