# Generated by Django 6.1 on 2026-08-12 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_savingsgoal_account_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingsgoal',
            name='account_number',
        ),
    ]
