# Generated by Django 6.1 on 2026-08-13 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        ('transactions', '0005_remove_savingsgoal_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_partial',
            field=models.BooleanField(default=False, help_text='True when a loan repayment only covers part of the outstanding balance.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='loan',
            field=models.ForeignKey(blank=True, help_text='Loan this transaction relates to (for repayments).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='loans.loan'),
        ),
    ]
