# Generated by Django 6.1 on 2026-08-13 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_is_partial_transaction_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='goaltransaction',
            name='reference',
            field=models.CharField(blank=True, help_text='System-generated transaction reference code (10-12 uppercase alphanumeric characters)', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference',
            field=models.CharField(blank=True, help_text='System-generated transaction reference code (10-12 uppercase alphanumeric characters)', max_length=12, null=True, unique=True),
        ),
    ]
