# Generated by Django 6.1 on 2026-08-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_backfill_transaction_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='broker_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='transaction',
            name='government_tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
