# Generated by Django 6.1 on 2026-08-21 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_seed_fx_crypto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(max_length=10, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('memo', models.CharField(blank=True, default='', max_length=140)),
                ('due_date', models.DateField(blank=True, help_text='Post-dated cheques cannot be cleared before this date.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled'), ('stopped', 'Stopped')], default='pending', max_length=10)),
                ('status_note', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('cleared_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques_issued', to=settings.AUTH_USER_MODEL)),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
