# Generated by Django 6.1 on 2026-08-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie_photo',
            field=models.ImageField(blank=True, null=True, upload_to='selfies/'),
        ),
    ]
