# Generated by Django 6.1 on 2026-08-10 17:01

from django.db import migrations, models
import secrets
import string


def generate_account_number():
    return ''.join(secrets.choice(string.digits) for _ in range(12))


def populate_account_numbers(apps, schema_editor):
    User = apps.get_model('core', 'User')
    db_alias = schema_editor.connection.alias
    
    existing_numbers = set(
        User.objects.using(db_alias).values_list('account_number', flat=True)
        .exclude(account_number=None)
        .exclude(account_number='')
    )
    
    for user in User.objects.using(db_alias).all():
        if not user.account_number:
            while True:
                new_num = generate_account_number()
                if new_num not in existing_numbers:
                    existing_numbers.add(new_num)
                    break
            user.account_number = new_num
            user.save(update_fields=['account_number'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_id_photo_user_profile_photo_user_selfie_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, help_text='Unique account number generated on user creation', max_length=12),
        ),
        migrations.RunPython(populate_account_numbers, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, help_text='Unique account number generated on user creation', max_length=12, unique=True),
        ),
    ]
