# Generated by Django 6.1 on 2026-08-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loan_wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
