# Generated by Django 6.1 on 2026-08-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_loan_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chama_wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='user',
            name='goal_wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
