# Generated by Django 6.1 on 2026-08-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Loyalty points balance used to redeem rewards.'),
        ),
    ]
