# Generated by Django 4.2.30 on 2026-08-15 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import random
import string


def backfill_referral_codes(apps, schema_editor):
    User = apps.get_model('core', 'User')
    existing = set(
        User.objects.exclude(referral_code='').values_list('referral_code', flat=True)
    )
    chars = string.ascii_uppercase + string.digits
    for user in User.objects.filter(referral_code=''):
        while True:
            code = ''.join(random.choices(chars, k=8))
            if code not in existing:
                break
        existing.add(code)
        user.referral_code = code
        user.save(update_fields=['referral_code'])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_businessanalytics_analyticsdashboard'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessAnalytics',
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Unique referral code shared with friends to earn points.', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='User who referred this account.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_referral_codes, noop),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Unique referral code shared with friends to earn points.', max_length=8, unique=True),
        ),
    ]
