# Generated by Django 6.1 on 2026-08-21 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_businessanalytics_user_referral_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentQrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=24, unique=True)),
                ('payload', models.TextField(help_text='JSON string encoded inside the QR image')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_qr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
